// import type { Metadata } from 'next'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

import SideBarO from '@/app/components/sideBar/SideBarO'
import TheUsers from './components/TheUsers'
import { getUsers } from '@/app/action/getUsers'

export default async function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  const users = await getUsers()


  return (
    <div className="h-screen">
      <SideBarO>
        <TheUsers
         users={users}
          />
        {children}
      </SideBarO>
    </div>
  )
}
