import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ToasterContext from './context/ToasterContext'
import AuthSession from './context/AuthSession'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  adjustFontFallback: false,
})
export const metadata: Metadata = {
  title: 'Chat Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" href="/images/save.jpg" />
        <title>Chat Application</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <AuthSession>
          <ToasterContext />
          {children}
        </AuthSession>
      </body>
    </html>
  )
}
